version: "3.7"

services:
  sharpfiles:
    hostname: sharpfiles
    image: sharp6292/sharpfiles

    volumes:
      - mcaq_sharex:/sharex/files/

    environment:
      - SECRET=${SHAREXPASS:?err}
      - DOMAIN=${DOMAIN:?err}

    restart: always

volumes:
  mcaq_sharex:
    external: True

networks:
    default:
        external:
            name: sharpnet
